export const REQUEST_INIT = "REQUEST_INIT";

export const FETCH_RESERVATIONS_SUCCESS = "FETCH_RESERVATIONS_SUCCESS";
export const CREATE_RESERVATION = "CREATE_RESERVATION";
export const DELETE_RESERVATION = "DELETE_RESERVATION";
export const DELETE_MODAL_SHOW = "DELETE_MODAL_SHOW";
export const DELETE_MODAL_CLOSE = "DELETE_MODAL_CLOSE";

export const REQUEST_FAILED = "REQUEST_FAILED";
